# Generated by Django 3.1.5 on 2021-01-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airplane_Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=150)),
            ],
            options={
                'unique_together': {('passport_number', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weekdays', models.CharField(max_length=120)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_airline', to='mainapp.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Leg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leg_number', models.CharField(max_length=20)),
                ('scheduled_departure_time', models.TimeField()),
                ('scheduled_arrival_time', models.TimeField()),
                ('arrival_airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_arrival_ac', to='mainapp.airport')),
                ('departure_airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_departure_ac', to='mainapp.airport')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_flight_number', to='mainapp.flight')),
            ],
            options={
                'unique_together': {('flight_number', 'leg_number')},
            },
        ),
        migrations.CreateModel(
            name='Leg_Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_of_available_seats', models.IntegerField()),
                ('departue_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_id', to='mainapp.airplane')),
                ('arrival_arport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legInstance_arrival_ac', to='mainapp.airport')),
                ('departure_airport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legInstance_aparture_ac', to='mainapp.airport')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legInstance_flight_number', to='mainapp.flight_leg')),
                ('leg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legInstance_leg_number', to='mainapp.flight_leg')),
            ],
            options={
                'unique_together': {('flight_number', 'leg_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('company_name', 'contact_number')},
            },
        ),
        migrations.CreateModel(
            name='Airplane_Type',
            fields=[
                ('airplane_type_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('max_seats', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplane_company', to='mainapp.airplane_manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='airplane_manufacturer',
            name='company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='airplane_manufacturer_company', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airplane_manufacturer',
            name='contact_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='airplane_manufacturer_contact', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplane_airplane_type', to='mainapp.airplane_type'),
        ),
        migrations.AddField(
            model_name='airline',
            name='company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='airline_company', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airline',
            name='contact_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='airline_contact', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='airline',
            name='using_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_using_ap', to='mainapp.airport'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_country', to='mainapp.customer')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_date', to='mainapp.leg_instance')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_flight_number', to='mainapp.leg_instance')),
                ('leg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_leg_number', to='mainapp.leg_instance')),
                ('passport_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_passport_number', to='mainapp.customer')),
            ],
            options={
                'unique_together': {('flight_number', 'leg_number', 'date', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='FFC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('milleage', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffc_country', to='mainapp.customer')),
                ('passport_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffc_passport_number', to='mainapp.customer')),
            ],
            options={
                'unique_together': {('passport_number', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fare_code', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('restrictions', models.TextField()),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_flight_number', to='mainapp.flight')),
            ],
            options={
                'unique_together': {('flight_number', 'fare_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='airplane_manufacturer',
            unique_together={('company_name', 'contact_number')},
        ),
        migrations.AlterUniqueTogether(
            name='airline',
            unique_together={('company_name', 'contact_number')},
        ),
    ]
