# Generated by Django 3.1.5 on 2021-01-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
